#配置资源文件
name: kuangchang_app
description: A new Flutter project.

publish_to: 'none' # 如果不发布到pub.dev上可以删除这行

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.3
  shake_animation_widget: ^3.0.3
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  gzx_dropdown_menu: ^3.1.0
  image_picker: ^0.8.6
  flutter_swiper_null_safety: ^1.0.2
#其他依赖
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.2.0
  socket_io_client: ^2.0.0
  protoc_plugin: ^20.0.1
  protobuf: ^2.1.0
  fixnum: ^1.0.1
  get: ^4.6.5
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  #添加资源文件
  assets:
    - image/9ab516426a392a03f7f3af14d2588726a2.png
    - image/9ab516426a392a03f7f3af14d2588726bf.png
    - image/9ab516426a392a03f7f3af14d2588726ex.png
    - image/9ab516426a392a03f7f3af14d2588726ms.png
    - image/9ab516426a392a03f7f3af14d25887265q.png
