// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateAvatar.proto

#include "UpdateAvatar.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace UpdateAvatar_proto {
PROTOBUF_CONSTEXPR UpdateAvatar_request::UpdateAvatar_request(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.account_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.avatar_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateAvatar_requestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateAvatar_requestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateAvatar_requestDefaultTypeInternal() {}
  union {
    UpdateAvatar_request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateAvatar_requestDefaultTypeInternal _UpdateAvatar_request_default_instance_;
PROTOBUF_CONSTEXPR UpdateAvatar_reply::UpdateAvatar_reply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.issuccess_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UpdateAvatar_replyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateAvatar_replyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateAvatar_replyDefaultTypeInternal() {}
  union {
    UpdateAvatar_reply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateAvatar_replyDefaultTypeInternal _UpdateAvatar_reply_default_instance_;
}  // namespace UpdateAvatar_proto
static ::_pb::Metadata file_level_metadata_UpdateAvatar_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_UpdateAvatar_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_UpdateAvatar_2eproto = nullptr;

const uint32_t TableStruct_UpdateAvatar_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::UpdateAvatar_proto::UpdateAvatar_request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::UpdateAvatar_proto::UpdateAvatar_request, _impl_.account_),
  PROTOBUF_FIELD_OFFSET(::UpdateAvatar_proto::UpdateAvatar_request, _impl_.avatar_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::UpdateAvatar_proto::UpdateAvatar_reply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::UpdateAvatar_proto::UpdateAvatar_reply, _impl_.issuccess_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::UpdateAvatar_proto::UpdateAvatar_request)},
  { 8, -1, -1, sizeof(::UpdateAvatar_proto::UpdateAvatar_reply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::UpdateAvatar_proto::_UpdateAvatar_request_default_instance_._instance,
  &::UpdateAvatar_proto::_UpdateAvatar_reply_default_instance_._instance,
};

const char descriptor_table_protodef_UpdateAvatar_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022UpdateAvatar.proto\022\022UpdateAvatar_proto"
  "\"7\n\024UpdateAvatar_request\022\017\n\007account\030\001 \001("
  "\t\022\016\n\006avatar\030\002 \001(\t\"\'\n\022UpdateAvatar_reply\022"
  "\021\n\tissuccess\030\001 \001(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_UpdateAvatar_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_UpdateAvatar_2eproto = {
    false, false, 146, descriptor_table_protodef_UpdateAvatar_2eproto,
    "UpdateAvatar.proto",
    &descriptor_table_UpdateAvatar_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_UpdateAvatar_2eproto::offsets,
    file_level_metadata_UpdateAvatar_2eproto, file_level_enum_descriptors_UpdateAvatar_2eproto,
    file_level_service_descriptors_UpdateAvatar_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_UpdateAvatar_2eproto_getter() {
  return &descriptor_table_UpdateAvatar_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_UpdateAvatar_2eproto(&descriptor_table_UpdateAvatar_2eproto);
namespace UpdateAvatar_proto {

// ===================================================================

class UpdateAvatar_request::_Internal {
 public:
};

UpdateAvatar_request::UpdateAvatar_request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:UpdateAvatar_proto.UpdateAvatar_request)
}
UpdateAvatar_request::UpdateAvatar_request(const UpdateAvatar_request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateAvatar_request* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.account_){}
    , decltype(_impl_.avatar_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_account().empty()) {
    _this->_impl_.account_.Set(from._internal_account(), 
      _this->GetArenaForAllocation());
  }
  _impl_.avatar_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.avatar_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_avatar().empty()) {
    _this->_impl_.avatar_.Set(from._internal_avatar(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:UpdateAvatar_proto.UpdateAvatar_request)
}

inline void UpdateAvatar_request::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.account_){}
    , decltype(_impl_.avatar_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.avatar_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.avatar_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UpdateAvatar_request::~UpdateAvatar_request() {
  // @@protoc_insertion_point(destructor:UpdateAvatar_proto.UpdateAvatar_request)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateAvatar_request::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.account_.Destroy();
  _impl_.avatar_.Destroy();
}

void UpdateAvatar_request::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateAvatar_request::Clear() {
// @@protoc_insertion_point(message_clear_start:UpdateAvatar_proto.UpdateAvatar_request)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_.ClearToEmpty();
  _impl_.avatar_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateAvatar_request::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string account = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_account();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "UpdateAvatar_proto.UpdateAvatar_request.account"));
        } else
          goto handle_unusual;
        continue;
      // string avatar = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_avatar();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "UpdateAvatar_proto.UpdateAvatar_request.avatar"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdateAvatar_request::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UpdateAvatar_proto.UpdateAvatar_request)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string account = 1;
  if (!this->_internal_account().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_account().data(), static_cast<int>(this->_internal_account().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "UpdateAvatar_proto.UpdateAvatar_request.account");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_account(), target);
  }

  // string avatar = 2;
  if (!this->_internal_avatar().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_avatar().data(), static_cast<int>(this->_internal_avatar().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "UpdateAvatar_proto.UpdateAvatar_request.avatar");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_avatar(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UpdateAvatar_proto.UpdateAvatar_request)
  return target;
}

size_t UpdateAvatar_request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UpdateAvatar_proto.UpdateAvatar_request)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account = 1;
  if (!this->_internal_account().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_account());
  }

  // string avatar = 2;
  if (!this->_internal_avatar().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_avatar());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateAvatar_request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateAvatar_request::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateAvatar_request::GetClassData() const { return &_class_data_; }


void UpdateAvatar_request::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateAvatar_request*>(&to_msg);
  auto& from = static_cast<const UpdateAvatar_request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UpdateAvatar_proto.UpdateAvatar_request)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account().empty()) {
    _this->_internal_set_account(from._internal_account());
  }
  if (!from._internal_avatar().empty()) {
    _this->_internal_set_avatar(from._internal_avatar());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateAvatar_request::CopyFrom(const UpdateAvatar_request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UpdateAvatar_proto.UpdateAvatar_request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateAvatar_request::IsInitialized() const {
  return true;
}

void UpdateAvatar_request::InternalSwap(UpdateAvatar_request* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.account_, lhs_arena,
      &other->_impl_.account_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.avatar_, lhs_arena,
      &other->_impl_.avatar_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateAvatar_request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_UpdateAvatar_2eproto_getter, &descriptor_table_UpdateAvatar_2eproto_once,
      file_level_metadata_UpdateAvatar_2eproto[0]);
}

// ===================================================================

class UpdateAvatar_reply::_Internal {
 public:
};

UpdateAvatar_reply::UpdateAvatar_reply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:UpdateAvatar_proto.UpdateAvatar_reply)
}
UpdateAvatar_reply::UpdateAvatar_reply(const UpdateAvatar_reply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UpdateAvatar_reply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.issuccess_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.issuccess_ = from._impl_.issuccess_;
  // @@protoc_insertion_point(copy_constructor:UpdateAvatar_proto.UpdateAvatar_reply)
}

inline void UpdateAvatar_reply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.issuccess_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UpdateAvatar_reply::~UpdateAvatar_reply() {
  // @@protoc_insertion_point(destructor:UpdateAvatar_proto.UpdateAvatar_reply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UpdateAvatar_reply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void UpdateAvatar_reply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UpdateAvatar_reply::Clear() {
// @@protoc_insertion_point(message_clear_start:UpdateAvatar_proto.UpdateAvatar_reply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.issuccess_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateAvatar_reply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool issuccess = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.issuccess_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdateAvatar_reply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UpdateAvatar_proto.UpdateAvatar_reply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool issuccess = 1;
  if (this->_internal_issuccess() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_issuccess(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UpdateAvatar_proto.UpdateAvatar_reply)
  return target;
}

size_t UpdateAvatar_reply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UpdateAvatar_proto.UpdateAvatar_reply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool issuccess = 1;
  if (this->_internal_issuccess() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateAvatar_reply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UpdateAvatar_reply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateAvatar_reply::GetClassData() const { return &_class_data_; }


void UpdateAvatar_reply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UpdateAvatar_reply*>(&to_msg);
  auto& from = static_cast<const UpdateAvatar_reply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UpdateAvatar_proto.UpdateAvatar_reply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_issuccess() != 0) {
    _this->_internal_set_issuccess(from._internal_issuccess());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateAvatar_reply::CopyFrom(const UpdateAvatar_reply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UpdateAvatar_proto.UpdateAvatar_reply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateAvatar_reply::IsInitialized() const {
  return true;
}

void UpdateAvatar_reply::InternalSwap(UpdateAvatar_reply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.issuccess_, other->_impl_.issuccess_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateAvatar_reply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_UpdateAvatar_2eproto_getter, &descriptor_table_UpdateAvatar_2eproto_once,
      file_level_metadata_UpdateAvatar_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace UpdateAvatar_proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::UpdateAvatar_proto::UpdateAvatar_request*
Arena::CreateMaybeMessage< ::UpdateAvatar_proto::UpdateAvatar_request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::UpdateAvatar_proto::UpdateAvatar_request >(arena);
}
template<> PROTOBUF_NOINLINE ::UpdateAvatar_proto::UpdateAvatar_reply*
Arena::CreateMaybeMessage< ::UpdateAvatar_proto::UpdateAvatar_reply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::UpdateAvatar_proto::UpdateAvatar_reply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
